websocket:
  connector:
    server:
      readIdleSecond: 0
      writeIdleSecond: 0
      allIdleSecond: 360
      sendBuff: -1
      recvBuff: -1
      backlog: 500000
      bossThreads: 1
      connTimeoutMills: 10000
      soLinger: 0
      port: 8763
      reuseAddr: true
      useDirectBuffer: true
      useEpoll: true
      useMemPool: true
      userThreads: 50
      workerThreads: 0
      idleTimes: 5
