eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769
spring:
  application:
    name: api-gateway
  profiles:
    active: redis
  cloud:
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: 47.113.83.248:9092,47.115.25.186:9092,47.113.81.159:9092

management:
  endpoints:
    web:
      exposure:
        include: '*'

zuul:
  add-proxy-headers: true
  sensitive-headers:
  routes:
    api-user:
      path: /api-user/**
      serviceId: account



