spring:
  redis:
    password: 123456
    cluster:
      nodes:
           47.113.83.248:7001,
           47.113.83.248:7002,
           47.115.25.186:7003,
           47.115.25.186:7004,
           47.113.81.159:7005,
           47.113.81.159:7006
      lettuce:
        pool:
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 5  # 连接池中的最小空闲连接
          max-wait-millis: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-redirects: 3
    timeout: 5000

