server:
  port: 8761

eureka:
  instance:
    hostname: 47.113.83.248

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

spring:
  application:
    name: eureka-server

