server:
  port: 8768
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CrazyMan-Chenlin/config-server.git
          search-paths: '{application}'
    bus:
      refresh:
        enabled: true
  application:
    name: config-server
  kafka:
    bootstrap-servers: 47.113.83.248:9092,47.115.25.186:9092,47.113.81.159:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'